%.so: %.o
	gcc -g -O2 -shared -o $@ $< `python-config --ldflags`
	install_name_tool -change /System/Library/Frameworks/Python.framework/Versions/2.7/Python /usr/local/anaconda/lib/libpython2.7.dylib $@


%.o: %.c
	gcc -g -O2 -fpic -DWITH_THREAD=1 -c $< -o $@ `python-config --includes` -I`python -c "import numpy; print numpy.get_include()"`


%.c: %.pyx
	cython $<