spwfinder.so:
	cython plugin.pyx
	gcc -g -O2 -fpic -c plugin.c -o plugin.o `python-config --includes` -I`python -c "import numpy; print numpy.get_include()"`
	gcc -g -O2 -shared -o spwfinder.so plugin.o `python-config --ldflags` -L../../python-libs/ -Wl,-rpath=../../python-libs

clean:
	rm -f plugin.c plugin.h *.o *.so
