SOURCE_DIR = $(shell dirname $(dirname $(pwd) ) )
all:
	cython plugin.pyx
	gcc -g -O2 -fpic  -DWITH_THREAD=1 -c plugin.c -o plugin.o `python-config --includes` -I`python -c "import numpy; print numpy.get_include()"`
	gcc -g -O2 -shared -o pulse_test_delay.so plugin.o `python-config --ldflags` -L$(SOURCE_DIR)/../../python-libs -Wl,-rpath=$(SOURCE_DIR)/../../python-libs
	cp pulse_test_delay.so plugin.so
clean:
	rm -f plugin.c plugin.h *.o *.so
